# Generated by Django 5.2.12 on 2026-03-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=255)),
                ('halaman', models.IntegerField()),
                ('tahun_terbit', models.IntegerField()),
                ('sampul_buku', models.ImageField(upload_to='sampul/')),
            ],
        ),
    ]
