name: CI/CD Final Project

on:
  push:
    branches: ["main", "testing"]
  pull_request:
    branches: ["testing", "main"]

jobs:
  # job pertama: deteksi perubahan file dan folder
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      django: ${{ steps.filter.outputs.django }}
      data: ${{ steps.filter.outputs.data }}
      proxy: ${{ steps.filter.outputs.proxy }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            django:
              - "django-app/**"
            data:
              - "database-postgres/**"
            proxy:
              - "proxy-nginx/**"

  # job 2 : build image django nya
  build-django:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.django == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Set Tag # memisahkan tag testing dengan tag latest untuk produksi dan testing
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else 
            echo "IMAGE_TAG=testing" >> $GITHUB_ENV
          fi
      - name: Login ke Docker Hub Alya # yang ngurus django
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_ALYA }}
          password: ${{ secrets.DOCKERHUB_TOKEN_ALYA }}

      - name: Build & Push image django
        uses: docker/build-push-action@v4
        with:
          context: ./django-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_ALYA }}/bookstorage-django:${{ env.IMAGE_TAG }}

  # job 3: build image database (postgresql dan minio)
  build-data:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.data == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Set Tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else 
            echo "IMAGE_TAG=testing" >> $GITHUB_ENV
          fi

      - name: Login Dockerhub Danur # yang ngurus database
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_DANUR }}
          password: ${{ secrets.DOCKERHUB_TOKEN_DANUR }}

      - name: Build & Push image postgresql
        uses: docker/build-push-action@v4
        with:
          context: ./database-postgres
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_DANUR }}/bookstorage-postgresql:${{ env.IMAGE_TAG }}

      - name: Build & Push image minio
        uses: docker/build-push-action@v4
        with:
          context: ./storage-minio
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_DANUR }}/bookstorage-minio:${{ env.IMAGE_TAG }}

  # Job 4 : build & push proxy & monitoring (devops belom tau contextnya (Dockerfile) ada di mana )
  build-proxy-monitoring:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.proxy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Set Tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main "]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else 
            echo "IMAGE_TAG=testing" >> $GITHUB_ENV
          fi

      - name: Login Docker Hub Dzakky # yang ngurus nginx dan monitoring
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_DZAKKY }}
          password: ${{ secrets.DOCKERHUB_TOKEN_DZAKKY }}

      - name: Build & Push image Nginx
        uses: docker/build-push-action@v4
        with:
          context: ./proxy-nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_DZAKKY }}/bookstorage-nginx:${{ env.IMAGE_TAG }}

      - name: Build & Push image Prometheus
        uses: docker/build-push-action@v4
        with:
          context: ./monitoring/prometheus
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_DZAKKY }}/bookstorage-prometheus:${{ env.IMAGE_TAG }}

      - name: Build & Push image Grafana
        uses: docker/build-push-action@v4
        with:
          context: ./monitoring/grafana
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_DZAKKY }}/bookstorage-grafana:${{ env.IMAGE_TAG }}
